/* Dataset didascalie della mostra "Vincenzo Jentile, il maestro fotografo"
   Fonte: Didascalie-Mazzella.pdf — un elemento per ogni lastra fotografica (1-150) */
const GALLERY_DATA = [
  { id: 1, caption: "Coniugi Cristina Barillaro (1851-1943) fu Nicola e Salvatore Ientile (1847-1930) fu Rosa, piccoli proprietari terrieri, genitori di Vincenzo Jentile" },
  { id: 2, caption: "Salvatore Ientile, Cristina Barillaro e nipoti, casa di via Serra S. Bruno (attuale via G. Oberdan 25)" },
  { id: 3, caption: "Vincenzo Jentile (1890-1966) fu Salvatore, maestro elementare. Autoscatto?" },
  { id: 4, caption: "Vincenzo Jentile (1890-1966) fu Salvatore, maestro elementare." },
  { id: 5, caption: "Raffaele Ientile fu Salvatore, ispettore scolastico" },
  { id: 6, caption: "Antonietta Barillaro fu Raffaele con la figlia Ersilia Ientile" },
  { id: 7, caption: "Ersilia, Eleonora e Enzo Ientile di Raffaele, sul terrazzino della casa del loro zio Vincenzo Ientile, in via Serra S. Bruno (ora G. Oberdan 25)" },
  { id: 8, caption: "Francesco Barillaro (1904), Alfonsina Ientile (1879) e figli, Peppino Cordì, Francesco Barillaro (1873), Guglielmo Barillaro (1902), Jolanda Barillaro (1912, in braccio al padre), Vincenzo Barillaro (1909), Attilio Barillaro (1914), Raffaele Barillaro (1906) – 1917 circa" },
  { id: 9, caption: "Giuseppe Chirico da Catona (RC), segretario comunale. Secondo marito di M. Teresa Barillaro fu Nicola, si risposò a sua volta con M. Giuseppa Scali, padre di Elvira Chirico, madre di Luigino Nadile." },
  { id: 10, caption: "“U Malabestia”" },
  { id: 11, caption: "Liberto “Libè d'u barveri”, nipote del barbiere Domenicantonio" },
  { id: 12, caption: "“Michjè” da Grotteria, garzone del massaro Squillace (Mbutu), trovatello originario di Grotteria, ammazzato a S. Giovanni (dal “Timpunaru”)?" },
  { id: 13, caption: "Don Gustinu?" },
  { id: 14, caption: "Figlia di Filomena?" },
  { id: 15, caption: null },
  { id: 16, caption: null },
  { id: 17, caption: "Giuseppe (Peppino) Nigro, fu Nicola. Sua nonna materna (Maria Filomena Barillaro) era sorella del notaio Nicola Barillaro. Sposò Vincenzina Vumbaca di Francesco Antonio" },
  { id: 18, caption: "Raffaele Nadile (1899-1972), fu Vincenzo, pittore." },
  { id: 19, caption: "Eugenio Nadile (1892-1916), fu Vincenzo." },
  { id: 20, caption: "Domenico Nadile “Barveja” (1897-1966), fu Vincenzo." },
  { id: 21, caption: "Filomena Barillaro, con la figlia Rosina Nesci. Rosina Nesci, fu Ferdinando, e sua madre Filomena Barillaro (1870-1951), fu Nicola." },
  { id: 22, caption: "Cristina Nadile fu Vincenzo (1906-19__), Rosina Nesci* fu Ferdinando (1902?), Emilia Nadile fu Vincenzo (1904-____). *morta di tubercolosi" },
  { id: 23, caption: "Vincenzina Ientile, con le figlie Emilia e Cristina Nadile." },
  { id: 24, caption: "Giuseppe (Peppino) Vumbaca fu Francesco Antonio, mestro elementare. In divisa da artiglieria da montagna, Iª guerra mondiale." },
  { id: 25, caption: "Gaetano Vumbaca, fratello di Carmelo. Emigrato temporaneamente in Argentina." },
  { id: 26, caption: "Salvatore Vumbaca “U Licinaru”, marito della “barijara”." },
  { id: 27, caption: "Fratelli Vumbaca I - Giosì Vumbaca; II - ?; III - Elisabetta Vumbaca fu Fortunato e di Raff. M. Teresa Calabrò (“A Russa”)" },
  { id: 28, caption: "Giuseppe Scali “U Bardonecchja” (avendo fatto il servizio di leva proprio a Bardonecchia, TO), barbiere e cavadenti. Per fare la barba a coloro che erano senza denti gli faceva mettere in bocca una patata." },
  { id: 29, caption: "Ettore Viri “Esterinu u Michjelè”. Figlio spurio di G. B, Lucà “costata”." },
  { id: 30, caption: "Maria Giuseppa Carella e figli (emigrati in Australia). “a careja”, tessitrice." },
  { id: 31, caption: "Raffaele Santini, muratore." },
  { id: 32, caption: "Rosa Trimboli “Maddamma Rosa i Rachjela”." },
  { id: 33, caption: "Salvatore Papandrea “U Bombecchju”, morto sepolto durante lo scavo per la costruzione di una briglia a Mannò, dopo l'alluvione del 1932." },
  { id: 34, caption: "Nicola Papandrea “U Mperreja”" },
  { id: 35, caption: "Vincenzo Papandrea “U Mamà”, marito di Antonietta Prigitano." },
  { id: 36, caption: "Saverio Papandrea, cognato del “Turicchju”." },
  { id: 37, caption: "Raffaele Pata da Seminara, decoratore." },
  { id: 38, caption: "Teresina Pittari, pasticcera da Martone, maritata Alberto Macrì dolciere di Martone." },
  { id: 39, caption: "Immacolata Prigitano “A Catarineja” colona in Libia, fu Salvatore, sorella di Domenico Prigitano (Cumpari Micuzzu), fu in Libia insieme al marito Salvatore Gaglioti con i coloni italiani – “a Catarinella”" },
  { id: 40, caption: "Rosario Rinaldis, calzolaio emigrato in Uruguay." },
  { id: 41, caption: "Francesco Papandrea “U Calanaru”, contadino." },
  { id: 42, caption: "Ferdinando Papandrea “U Calanaru”, fu Francesco contadino." },
  { id: 43, caption: "Don Raffaele Papandrea “U Stràscina”, sacerdote." },
  { id: 44, caption: "Vincenzo Papandrea “U Stràscina”, figlio di Fortunato." },
  { id: 45, caption: "Giuseppe Papandrea “Don Peppinu i Mastru Tomasi”, “U Jancu”, possidente." },
  { id: 46, caption: "Salvatore Papandrea, futuro dentista in Napoli, fu Giuseppe “Don Peppinu i Matru Tomasi”" },
  { id: 47, caption: "Maria Francesca Papandrea “Peppina d'a Jina”, fu Domenico Antonio e Teresa Vumbaca." },
  { id: 48, caption: "Immacolata e Stella Papandrea “d'a Jina”, figlie di Maria Francesca Papandrea." },
  { id: 49, caption: "Luigi Muratore “Loì u Pirolè” o “U Mujura”, ucciso da Peppi Leo. I figli sono in Australia." },
  { id: 50, caption: "Giorgio Muscari “d'a Paccia” o “U Vavusu”, emigrato in Argentina. Ha sposato una sua cugina; il cugino Giovanni Muscari è presidente della Commissione della Festa della Madonna delle Grazie (Villa Dominico, prov. di Buenos Aires)" },
  { id: 51, caption: "Salvatore Napoli “U Bombinu”, emigrato in Australia." },
  { id: 52, caption: "Caterina Napoli “A Bombina”, emigrata in Australia." },
  { id: 53, caption: "Giuseppe Panetta “U Scarfaseggi”." },
  { id: 54, caption: "Salvatore Panetta da Grotteria, Direttore Scolastico." },
  { id: 55, caption: "Maria Teresa Dominello “A Testeferru”, maritata G.B. Papandrea e figlia della “Santadominica d'i lupi”" },
  { id: 56, caption: "Maria Giuseppa Papandrea, fu G.B." },
  { id: 57, caption: "Raffaele Mesiti “U Culivecchja”." },
  { id: 58, caption: "Giuseppe Mesiti “U Mulinaru”. I figli residenti in Argentina sono morti. Il figlio Salvatore è in Australia ed è vivo. Nipote e genero di Fortunato Mesiti." },
  { id: 59, caption: "Fortunato Mesiti “U Mulinaru”, fratello di Giuseppe “u mulinaru”. Zio di Domenico Carabetta “cunigghjju”. I figli sono in Australia." },
  { id: 60, caption: "Ferdinando Mesiti “Nandu u Mulinaru”, figlio di Giuseppe, morto in Argentina. I figli sono in Argentina." },
  { id: 61, caption: "Giuseppe Mulè con il tipico copricapo detto “coppulinu c'u cimbulu”. Il fratello Rocco Vincenzo morì a 102 anni; il tipico copricapo maschile di forma conica e con un pendente (“pon-pon”) all'estremità, veniva spesso usato come contenitore di moneta; già all'epoca era quasi in disuso. Il nipote è in Argentina" },
  { id: 62, caption: "Vincenzo Mulè “U Noncennenti”." },
  { id: 63, caption: "Salvatore Mulè “U Prusdarinu”, padre del dentista Enzo Mulè." },
  { id: 64, caption: "Maria Giuseppa Mulè “A mbellarò”." },
  { id: 65, caption: "Maria Lucà, figlia di Cristina Malgeri (fu Giuseppe) e Franc. Ant. Lucà." },
  { id: 66, caption: "Salvatore Malgeri e Cecilia Caccamo con i figli Peppino, Isabella e Vincenzo* (*futuro sindaco di San Giovanni di Gerace)." },
  { id: 67, caption: "Giuseppe (Peppino) Malgeri, fu Salvatore." },
  { id: 68, caption: "Nice Bonvini e Nicolina Agostini (cognate). Moglie di Antonio Agostini e di Vincenzo Malgeri fu Giuseppe." },
  { id: 69, caption: "Vincenzina Marcellino, di Maria Carmela." },
  { id: 70, caption: "Maria Caterina Marcellino “A Mastricchja”. I figli sono in Australia." },
  { id: 71, caption: "Raffaele Marcellino Ardito a Fiume, emigrato in Australia (1901-1988). Agricoltore di fiori e verdure a Sidney, fece parte degli Arditi nell'impresa di Fiume; emigrò in Australia (1928) col nipote Carabetta Domenico (bersagliere 1915) con la nave “N. Cristina” (24-26/8/1928); promotore della realizzazione della statua della Madonna delle Grazie in Australia; marito della “Carolina”." },
  { id: 72, caption: "Pietro Marcellino emigrato in Australia." },
  { id: 73, caption: "Battista Malgeri con la figlia Giovannina Hyeraci, moglie di Salvatore Hyeraci “U Culonna”." },
  { id: 74, caption: "Salvatore Hyeraci “U Culonna” fu Giuseppe, marito di Battista Malgeri. Faceva il falso testimone." },
  { id: 75, caption: "Francesco Antonio Hyeraci postino, fu Giuseppe." },
  { id: 76, caption: "Salvatore Hyeraci, figlio del postino Francescantonio, fratello di Raffaele." },
  { id: 77, caption: "Giuseppe Hyeraci “Peppinu u Cucuzzuni” postino, o Jeraci? fu Francesco Saverio e M. Elisabetta Barillaro (sorella del notaio Nicola)." },
  { id: 78, caption: "Fortunata Malgeri e figlia (Giuseppina Prigitano) fu Fortunato, moglie di Domenico Prigitano “Cumpari Micuzzu”" },
  { id: 79, caption: "Vincenzo Nigro “U Petrantoni”, padre dell'ufficiale di posta Aldo Pietro Nigro." },
  { id: 80, caption: "Sabina Marchese fu Salvatore. Madre dell'ufficiale di posta Aldo Pietro Nigro." },
  { id: 81, caption: "Salvatore Lucà “U Costata”, “michjelè”/massaru." },
  { id: 82, caption: "Salvatore Lucà “U Costata” e figli." },
  { id: 83, caption: "Domenico Lucà “U Costata” emigrato in U.S.A. fu Fortunato. Padre del postino Francesco (soprannome dei figli “cocciciciari”)." },
  { id: 84, caption: "Tullio Licurgo “Roccu u Settanni”" },
  { id: 85, caption: "Vincenzo Maggio. I figli sono in Australia: Nicole, G.B., Immacolata. Marito di M. Teresa “a surda”." },
  { id: 86, caption: "Maria Caterina? moglie di Rocco Vincenzo Mulè e figli (Maria Raffaela, Immacolata, Rosa, Antonio, Peppina e Giovanni). Maria Raffaela, Immacolata → Argentina, Rosa → U.S.A., Antonio e Peppina → Torino, Giovanni → Argentina" },
  { id: 87, caption: "Aurelio Marcone “U Brunu”, marito della 'mbellarò." },
  { id: 88, caption: "Immacolata Vincenza Lucà “A Pepparella” e figlie (Amelia e Rosina) fu Giuseppe, vedova di G. Mulè “Donguglielmu”." },
  { id: 89, caption: "Luigi Raffaele Lucà fu Giuseppe e Filomena Schirripa, zio del prof. Francesco Mulè." },
  { id: 90, caption: "Marianna Lucà “A Pepparella” e figli (Carmelo, Raffaele, Rosina, Salvatore, Delizia e Genoveffa), maritata con Mastro P. Marando; Marianna emigrata in Argentina e tornata, Rosina e Carmelo ancora in Argentina." },
  { id: 91, caption: "Carmelo, Raffaele e Delizia Marando, figli di “mastru Pascali”." },
  { id: 92, caption: "Mariannina Bufalo con i figli gemelli (Francesco e Rosina Lucà), maritata Francesco Lucà." },
  { id: 93, caption: "Giovannina Lucà con i nipoti gemelli (Francesco e Rosina Lucà)." },
  { id: 94, caption: "Giovannina Lucà con la nipote Olga Barillaro. Cognata di Luigi Vincenzo Barillaro." },
  { id: 95, caption: "Emilio La Rosa “Migliu Piruni”" },
  { id: 96, caption: "Domenico Antonio Galluzzo “U Pirri”" },
  { id: 97, caption: "Domenico Giacco “U Casacca”, spazzino. Zio di Lillo Alù. Morto a Messina." },
  { id: 98, caption: "Caterina Giacco, zia? di Alexander F. Giacco, uomo d'affari italo-americano." },
  { id: 99, caption: "Rosa Caterina Giaconia e figlia, suocera di mastro Ciccio Masdea." },
  { id: 100, caption: "Francesco Guidaci “U Fondella” e figli, (G.B. Guidaci fratello?)" },
  { id: 101, caption: "Girolamo Iemma “U Gialò”" },
  { id: 102, caption: "Domenico Iemma “U Paleri”" },
  { id: 103, caption: "Vincenzo Jentile “U Perguleju” (da non confondere con l'omonimo maestro e fotografo dilettante)" },
  { id: 104, caption: "Domenico Galluzzo (?) “U Gozzaru” o “U Pilinà”, figlio del “Pilinà”, fratello di Maculata a Gozzara e marito di Jolanda Galluzzo." },
  { id: 105, caption: "Raffaele Galluzzo “U Frateju”, zio e marito di Letizia Galluzzo, suocero di Romualdo Naymo." },
  { id: 106, caption: "Letizia Galluzzo, suocera di Romualdo Naymo, nipote e moglie di Raffaele Galluzzo “A soru d'i ddu frati”" },
  { id: 107, caption: "Vincenzo Galluzzo “U Loigiuni” e figli (Letizia e ?), cugino d'u sirè (Salvatore)" },
  { id: 108, caption: "Salvatore Galluzzo “U Sirè” macellaio, padre di mastro Ciccio “sirè”?" },
  { id: 109, caption: "Salvatore Galluzzo “U Scancaratu” o “U Pipiggiarra”, nonno della ciunnareja, zio di Sarvaturi i Mannò. I figli sono emigrati in Australia." },
  { id: 110, caption: "Francesco Galluzzo “U Pantaluni”, cognato di Salvatore “U Palacciu”" },
  { id: 111, caption: "Raffaele Galluzzo “U Briganti”, zampognaro." },
  { id: 112, caption: "Domenicantonio Fazzolari “U Peppantò”, padre/zio di mastr'Angelo, marito di una “malizia”" },
  { id: 113, caption: "Giuseppe Fazzolari “U Peppantò”, i figli sono in Australia." },
  { id: 114, caption: "Don Domenico Ferraro, sacerdote" },
  { id: 115, caption: "Ferdinando Fortuna “U Dducoppi” emigrato in Argentina, “cofinaru”" },
  { id: 116, caption: "Giambattista Fuda, emigrato temporaneamente in U.S.A., padre di Rocco" },
  { id: 117, caption: "Rocco Fuda “U Prejera”, fratello di Mara Francisca, padre di Giovanni Fuda che è in Australia" },
  { id: 118, caption: "Salvatore Gaglioti “U Catarineja”, colono in Libia" },
  { id: 119, caption: "Vincenzo Gaglioti" },
  { id: 120, caption: "Francesco Carabetta “U Cunigghju”, contadino" },
  { id: 121, caption: "Francesco Antonio Carabetta “U Biscaru”" },
  { id: 122, caption: "? Carabetta “U Picinna”, figlio primogenito d'a picinna" },
  { id: 123, caption: "Giuditta Papandrea “A Picinna” con il figlio Vincenzo Carabetta (che è in Argentina), suocera di Matilde Marando" },
  { id: 124, caption: "Domenico D'Agostino “U Lattucaru”, emigrato temporaneamente in U.S.A., padre di Vincenzina “A Lattucara”" },
  { id: 125, caption: "Vincenzo De Luca “U Carrozzeri”, “Vicè i rosa”" },
  { id: 126, caption: "Rosa Maria De Maria “A Sonagghjera”" },
  { id: 127, caption: "Rocco De Maria “U Prestitu”, emigrato in Argentina, i figli sono in Argentina" },
  { id: 128, caption: "Giuseppe Caruso, piccolo proprietario" },
  { id: 129, caption: "Sabino Cavaleri “Sabinu i Mannò”, emigrato in Australia negli anni '30, fu Francesco, muratore e daziere. Cugino di Domenico Carabetta (1909-)" },
  { id: 130, caption: "Raffaele Cavaleri “U Santusapò”, emigrato in Australia. Figlio di M. Teresa d'a paccia, fratello di M. Elisabetta (stessa madre). I figli sono in Australia." },
  { id: 131, caption: "Giuseppe Cavaleri fu Carmelo" },
  { id: 132, caption: "Maria Teresa Cavaleri “A Cavalera”" },
  { id: 133, caption: "Giovanni Cessario “U Titta”" },
  { id: 134, caption: "Vincenzo Chimirri" },
  { id: 135, caption: "Elisabetta Cotrona e figlio, moglie di Cosimo Prudenzini?" },
  { id: 136, caption: "Maria Giuseppa Calabrò “Peppa a Marinara”" },
  { id: 137, caption: "Salvatore Papandrea “U Pugghju”" },
  { id: 138, caption: "Sorelle Maria Concetta, Maria Giuseppa, Immacolata ed Elisabetta Galluzzo fu Rocco" },
  { id: 139, caption: "Angelo Papandrea “U Pugghju”, emigrato in Australia fu Salvatore, marito di Bettina d'a Russa" },
  { id: 140, caption: "Giovanni e Raffaele Bruzzese “I Fàrfari”, emigrati in U.S.A. di Salvatore" },
  { id: 141, caption: "Fiorina Fazzolari “i Pascà d'u Barracca”, figlia di Peppina “a Piloja”" },
  { id: 142, caption: "Maria Giuseppa Galluzzo fu Rocco, Salvatore Papandrea “U Pugghjiu” e figli di cui Sofia, Angelo, Maddalena e Lisa (solo di lui) e Giovanni, il più piccolo di entrambi." },
  { id: 143, caption: "Rocco Agostino “U Rre d'Arceji”, emigrato in Argentina, in divisa da avanguardista" },
  { id: 144, caption: "Vincenzo Barillaro “U Piloju”" },
  { id: 145, caption: "Giorgio Barillaro “U Piloju”, emigrato in Australia. Suonava il clarinetto, studiato a Gioiosa Ionica" },
  { id: 146, caption: "Salvatore Barillaro “U Piloju”, padre di Carmelo" },
  { id: 147, caption: "Maria Rosa Barillaro “A Pòpula”, moglie di Cosimo Prudenzini" },
  { id: 148, caption: "Francesco Barillaro “U Salaru”" },
  { id: 149, caption: "Giuseppe Bevilacqua “U Mbivacqua”" },
  { id: 150, caption: "Enrico Bietola, detto Salvatore, emigrato in Australia, marito della “stignanota” M. Giuseppa" }
];
